version: 2

orbs:
  maven: circleci/maven@0.0.12
  codecov: codecov/codecov@1.1.1
  coveralls: coveralls/coveralls@1.0.4

general:
  branches:
    only:
      - master # list of branches to build
      - develop

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  build:

    docker:
      - image: circleci/openjdk:latest
      - image: circleci/postgres:latest

    steps:
      - checkout

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/Gruzoff-0.0.1-SNAPSHOT.jar

      - run: bash <(curl -s https://codecov.io/bash)

  deploy:
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
